blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.gg/Wupx8tHRVS
    about: Join our Discord for discussions and support
  - name: YouTube
    url: https://www.youtube.com/@smithplayspokemon
    about: Video tutorials and project updates
